# Generated by Django 5.1.3 on 2024-12-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_', '0002_remove_users_phone_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
