# Generated by Django 5.1.3 on 2024-12-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercards',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='UserCards',
        ),
    ]
