# Generated by Django 5.1.3 on 2024-12-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_', '0003_remove_usercards_user_id_delete_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('ADMIN', 'Admin'), ('DOCTOR', 'Doctor')], default='PATIENT', max_length=10),
        ),
    ]
