# Generated by Django 5.1.3 on 2024-12-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_', '0004_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
