# Generated by Django 5.1.3 on 2024-12-19 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dosage_form', models.CharField(choices=[('SYRUP', 'Syrup'), ('CREAM', 'Cream'), ('TABLET', 'Tablet'), ('CAPSULE', 'Capsule')], max_length=20)),
                ('strength', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('stock_quantity', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=255)),
                ('total_rating', models.FloatField(default=0.0)),
                ('rating_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medication_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.medications')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
