# Generated by Django 5.1.3 on 2024-12-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dosage_form', models.CharField(choices=[('SYRUP', 'Syrup'), ('CREAM', 'Cream'), ('TABLET', 'Tablet'), ('CAPSULE', 'Capsule')], max_length=20)),
                ('strength', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('stock_quantity', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
