# Generated by Django 5.1.3 on 2024-12-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctors_ratings_doctorrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorRating',
        ),
    ]
