# Generated by Django 5.1.3 on 2024-12-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
